// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_IB16WE_b98K09JsgAgs71Qvl-SMPvY8',
    appId: '1:337610044312:web:e7e6f644f48d264b17b1ed',
    messagingSenderId: '337610044312',
    projectId: 'online-turn-based-game',
    authDomain: 'online-turn-based-game.firebaseapp.com',
    storageBucket: 'online-turn-based-game.appspot.com',
    measurementId: 'G-Q2LHYHC4LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARPPWFVZ2w5oDzJY8E_EuJr2FgGePv8Rk',
    appId: '1:337610044312:android:1aa9fa2ef679929a17b1ed',
    messagingSenderId: '337610044312',
    projectId: 'online-turn-based-game',
    storageBucket: 'online-turn-based-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZfoyDsvrQpZBRchDMfemjPSf3QKqBi4',
    appId: '1:337610044312:ios:a15faa592060d91417b1ed',
    messagingSenderId: '337610044312',
    projectId: 'online-turn-based-game',
    storageBucket: 'online-turn-based-game.appspot.com',
    iosClientId: '337610044312-i0ld52v1u6nus6d09r852esn00j4qv4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnlineTurnBasedGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZfoyDsvrQpZBRchDMfemjPSf3QKqBi4',
    appId: '1:337610044312:ios:a15faa592060d91417b1ed',
    messagingSenderId: '337610044312',
    projectId: 'online-turn-based-game',
    storageBucket: 'online-turn-based-game.appspot.com',
    iosClientId: '337610044312-i0ld52v1u6nus6d09r852esn00j4qv4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnlineTurnBasedGame',
  );
}
